lib_imports
AlexandrGroz/auto_mo pull request #3
Opened 2024-06-05 21:25 UTC by Unaccommodating

2024-06-05 21:29 UTC, AlexandrGroz requested changes
Посмотри комментарии!

2024-06-05 21:29 UTC, AlexandrGroz commented on model_preparation.py
Тестим Request Changes #2
Добавь импорт numpy

2024-06-05 21:31 UTC, AlexandrGroz approved these changes
Молодец!

2024-06-06 05:54 UTC, nebrosarth approved these changes
Полезно...)

2024-06-06 05:56 UTC, merged